### ISSUE TITLE
Not working for last 3 items

### ISSUE THREAD

**Issue by kik4444** [cooljingle/memrise-auto-learn#1]
After one of the latest updates the effectiveness of the script has sort of declined in that it works flawlessly on the first 2 items in a set of 5, but not so much on the next 3.

**Comment by cooljingle** [comment]
I just did a quick test and it seemed to still be working for me - could it be just be to do with moving to a different page before the autolearn requests have completed?

**Comment by kik4444** [comment]
How long does it take to complete them?

**Comment by cooljingle** [comment]
should be just a few seconds but could be network dependent. I'll keep tabs on it to see if something weird is happening.

**Comment by cooljingle** [comment]
should be fixed now (0.0.9) - there was a memrise update which broke the script but the fix for it should completely eradicate your problem.

**Comment by kik4444** [comment]
It appears that the problem has arisen again.
