### ISSUE TITLE
Auto-Learn icon disappeared and script not functional

### ISSUE THREAD

**Issue by xuzumakii** [cooljingle/memrise-auto-learn#2]
Both Tamper Monkey and the script are enabled but whenever i learn new words f2 does not seem to activate anything . there is a red "1" on the tampermonkey icon in the top right corner when i start memrise    but it does not seem to do anything.
![capture](https://user-images.githubusercontent.com/37834921/37964178-4ea36620-320c-11e8-8dc0-9a88f245e452.PNG)

Hoping for a reply , thanks in advance.

**Comment by cooljingle** [comment]
should be fixed now (0.0.9)
