### ISSUE TITLE
Can the default option be 'on' instea of 'off'?

### ISSUE THREAD

**Issue by Avivhdr** [cooljingle/memrise-auto-learn#7]
Great Memrise scripts @cooljingle!

on every new word, the setting of auto-learn reverts to 'off'.
can it be configured?

Thanks

**Comment by Avivhdr** [comment]
I know see that it is configurable in the side settings.

**Comment by FireSeth** [comment]
I have no idea how to enable this setting. Can anyone help? @Avivhdr @cooljingle
